---
title: "Extract Data"
author: "Francine Stephens"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <- c(
  "readr",
  "tidyverse",
  "tidyr",
  "sf",
  "leaflet", 
  "readxl", 
  "mapboxapi",
  "tmap",
  "tmaptools",
  "tidycensus",
  "tigris",
  "geojsonio"
)
lapply(packages, library, character.only = TRUE)

## PATHS
wd <- getwd()

## PARAMETERS
wgs <- 4326
hill_country <- c("Comal", 
                  "Bexar", 
                  "Hays", 
                  "Travis", 
                  "Blanco", 
                  "Kendall", 
                  "Gillespie")
```


## S/CENTRAL TX COUNTIES

```{r}
counties_sf <- counties(state = "Texas")

```

```{r}
select_counties <- counties_sf %>% 
  filter(NAME %in% hill_country)

head(select_counties)
```

```{r}
aggregate_region_sf <- select_counties %>%
  group_by(STATEFP) %>% 
  summarize(counties = n()) %>% 
  ungroup()

geojson_write(aggregate_region_sf,
                         file = paste0("tx_geog/", "south_central_tx.GeoJSON"))

```
